rb_tree_node: 0-main.c 0-rb_tree_node.c rb_trees.h
	gcc -Wall -Wextra -Werror -pedantic 0-main.c 0-rb_tree_node.c rb_tree_print.c -o rb_tree_node
# 0-rb_tree_node.c: 0-main.c rb_trees.h
# 	gcc -Wall -Wextra -Werror -pedantic 0-main.c 0-rb_tree_node.c rb_tree_print.c -o rb_tree_node
